name: docker-pipeline-Pavithra
on: push
jobs:
  docker-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print your Register Number
        run: echo "Hello World - 22it028"

      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker Build
        run: docker build -t pavithrapalanisamy32/ml-model-22it028 .
        
      - name: Docker Image
        run: docker images
