name: docker-pipeline-Pavithra
on: push
jobs:
  docker-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print your Register Number
        run: echo "Hello World - 22it028"

      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker Build
        run: docker build -t pavithrapalanisamy32/ml-model-22it028 .
        
      - name: Docker Image
        run: docker images

       - name: Login to OCIR
         uses: docker/login-action@v3
         with:
          registry: <region>.ocir.io
          username: ${{ vars.OCI_USERNAME }}
          password: ${{ secrets.OCI_TOKEN }}
        - name: Docker Push
          run: docker push pavithrapalanisamy32/ml-model-22it028 .
        
